# Generated by Django 4.0.6 on 2022-10-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgardApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
